name: Java CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '17.0.1+12'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        brew install libavif
        mvn -B package --file pom.xml
